name: Detecting issue repeats

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: actions-cool/issues-similarity-analysis@v1
        id: analysis
        with:
          filter-threshold: 0.6
          title-excludes: 'bug, not'
          comment-title: '### 您的issue被检测到有重复主题，请先查看如下issue后再选择是否进行提问'
          comment-body: '${index}. ${similarity} #${number}'
          
#       - name: get_issue_number  
#         if: ${{ steps.analysis.outputs.similar-issues-found =='true' }}
#         uses: actions/github-script@v4
#         id: get_issue_number
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             const issueNumber = context.issue.number;
#             console.log(`Issue number is ${issueNumber}`);
#             return { issueNumber };
            
      - name: close issue 
        if: ${{ steps.analysis.outputs.similar-issues-found =='true' }}
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

