# name: Issues Similarity Analysis

# on:
#   issues:
#     types: [opened, edited]

# jobs:
#   similarity-analysis:
#     runs-on: ubuntu-latest
#     steps:
#       - name: analysis
#         uses: actions-cool/issues-similarity-analysis@v1
#         with:
#           filter-threshold: 0.7
#           title-excludes: 'bug, not'
#           comment-title: '### 您的issue被检测到有重复内容，请先查看如下issue后再选择是否进行提问'
#           comment-body: '${index}. ${similarity} #${number}'

name: Check for Duplicate Issues
on:
  issues:
    types: [opened]

jobs:
  check-for-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for duplicates and close them
        uses: dorny/autoclose@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
